Ejercicios de python con cosillas varias para poder manejarlo => actualizado Marzo 2024

In [1]:
# con esto importamos numpy
import numpy as np

In [ ]:
print(np.__version__) #con esto revisamos la versión correspondiente
np.show_config() #con esto se muestran datos técnicos de la instalación de numpy además de datos de la máquina

In [4]:
# creamos una cadena (matriz) de 10 ceros, recordar que estamos usando numpy
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# con esto se revisa el tamaño que utiliza este codigo (en este caso, una matriz)
z = np.zeros((10,10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


In [8]:
# crear una matriz de 9 ceros, pero en medio con un número uno
z = np.zeros(10)
z[4] = 1  #acá es donde se inserta el numero 1 en la cadena, esta se podría editar en cualquier posición
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# crear una matriz de 10x50 
z = np.arange(10,50)
print(z)


In [ ]:
# revertir una cadena o matriz
z = np.arange(50)
z = z[::-1] #esto es lo que realiza que la cadena se muestre de manera inversa
print(z)
# recordar que python parte de 0, por lo que el número final es el 49

In [ ]:
# crear una matriz de 3x3
z = np.arange(9).reshape(3,3) #acordarse del reshape, ya que es el fila/columna RECORDAR
print(z)

In [ ]:
# Devuelve los índices de los elementos distintos de cero.
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

In [ ]:
# crear una matiz identica de 3x3 con unos en diagonal
z = np.eye(10) #.reshape(20,5) el reshape lo dejé para jugar no más
print(z)

In [ ]:
# crear una matriz con datos random de 3 dimensiones
z = np.random.random((3,3,3))
print(z)

In [ ]:
# crear una matriz de 10x10 con datos random y encontrar sus minimos y maximos respectivos
z = np.random.random((10,10)) #genera la matriz
# print(z)
zmin,zmax = z.min(),z.max() #filtra los minimos y maximos de la cadena
print(zmin,zmax)

In [ ]:
# crear una matriz con datos random de 30 y encontrar la media
z = np.random.random((30)) #genera los datos de 30 valoresn en un array
# print(z)
m = z.mean() #busca el numero media del array
print(m)

In [ ]:
# sacarle los corchetes a los arrays
lista = np.arange(1,41).reshape(10,4) #genera el rango numerico y distribución fila columna
# cichlo for
for fila in lista:
    print(*fila)

COLORES EN PYTHON

In [ ]:
# Importar colorama - para agregar colorcillos en los textos
from colorama import *

In [ ]:
# colores de textos como ejemplos
print(Fore.CYAN + 'texto cyan')
print(Back.GREEN + 'background verde')
print(Style.DIM + 'and in dim text')
print(Style.RESET_ALL)
print('back to normal now')

In [ ]:
# crear una matriz 2d pero que sea rodeada de unos
# ejemplo
# 1 1 1 1
# 1 0 0 1
# 1 1 1 1
z = np.ones((10,10)) #crea una matriz de 10x10 
# print(z)
z[1:-1,1:-1] = 0
print(z)

In [ ]:
# agregar un borde con ceros en una matriz que ya existe
z = np.ones((5,5))
# print(z)
# np.pad en NumPy se utiliza para agregar relleno a un array NumPy. Puedes especificar el ancho del relleno y los valores de relleno para cada borde del array.
z = np.pad(z, pad_width=1, mode='constant', constant_values=0)
print(z)

In [ ]:
# usando un indexado más bonito para las matrices 
z = np.ones((10,10))

z[:, [0, -1]] = 0 # asigna el valor 0 a todas las filas de la primera y última columna de la matriz Z
z[[0, -1], :] = 0 # asigna el valor 0 a la primera y última fila de todas las columnas de la matriz Z
print(z)

In [ ]:
# resultado de la siguiente expresión
# ojo, nan es NaN = not a number
0 * np.nan
np.nan == np.nan # En NumPy, la comparación de NaN con NaN devuelve False, ya que NaN se considera un valor "no numérico
np.inf > np.nan # En NumPy, infinito (inf) se considera mayor que NaN, ya que NaN se considera un valor "no numérico
np.nan - np.nan # Restar NaN de NaN resulta en NaN
np.nan in set([np.nan]) # NaN está presente en el conjunto que contiene NaN, por lo tanto, devuelve True
0.3 == 3 * 0.1 # Debido a problemas de representación en punto flotante, esta expresión puede no dar como resultado True en todos los casos, ya que 0.1 no puede representarse con precisión en binario. Por lo tanto, puede dar como resultado False en algunos casos debido a errores de redondeo en la representación de números de punto flotante

In [ ]:
# crear una matriz de 5x5  con valores 1,2,3.4 justo debajo de la diagonal
z = np.diag(1+np.arange(4),k=-1)
print(z)

In [ ]:
# crear una matriz de 10x10 y generarla a lo tablero de ajedrez 1 0 1 0 1 
z = np.zeros((8,8), dtype=int) #el dtype quita los puntos de la matriz
z[1::2,::2] = 5
z[::2,1::2] = 1
print(z)

In [ ]:
# Considere una matriz de formas (6,7,8), ¿cuál es el índice (x,y,z) del elemento número 100?
matriz = np.unravel_index(99,(6,7,8))
print(matriz)

In [ ]:
# crear una matriz de 8x8 como ajedrez
z = np.tile(np.array([[0,5],[1,0]]), (4,4))
print(z)

In [ ]:
# normalizar una matriz aleatoria de 5x5
z = np.random.random((5,5))
print("matriz sin normalizar\n",z) #impresion de la matriz sin normalizar
z = (z - np.mean(z)) / (np.std(z)) # se resta la media y se divide por la desviaación estandar de la matriz
print("matriz normalizada\n",z)

In [ ]:
# multiplicar una matriz de 5x3 * 3x2
z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(z)


In [ ]:
# solución de arriba para versiones actuales de python
z = np.ones((5,3)) @ np.ones((3,2))
print(z)

In [ ]:
# realizar un array de 1D y dejar en negativo los elementos que estén entre el 3 y el 8
z = np.arange(10)
z[(3 < z) & (z < 8)] *= -1
print(z)

In [ ]:
print(np.array(0) / np.array(0)) # intenta dividir dos arrays, ambos conteniendo el valor 0. Esto generará un "warning" de división por cero y el resultado será nan (Not a Number) en un array de punto flotante.
print(np.array(0) // np.array(0)) # Similar al caso anterior, pero utilizando la división entera (//). También generará un "warning" de división por cero y el resultado será 0 en un array de tipo entero.
print(np.array([np.nan]).astype(int).astype(float)) #  Aquí se crea un array con un valor nan, luego se convierte a tipo entero (lo cual convierte nan a -9223372036854775808 en sistemas de 64 bits), y finalmente se convierte de nuevo a tipo flotante, resultando en -9.22337204e+18

In [ ]:
# redondear desde cero una matriz con numeros float
z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)),z))

In [ ]:
# más legible que el de arriba, pero menos eficiente
mat = np.where(z>0,np.ceil(z),np.floor(z))
print(mat)

In [ ]:
# Cómo encontrar valores comunes entre 2 arrays?
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
print("matrices random:\n",z1,z2)
print("numeros en común:\n", np.intersect1d(z1,z2))

ejemplos de fechas, tanto con librería datetime como con numpy

In [ ]:
import datetime # se importa la librería datetime
# obtener los formatos de fecha necesarios
fecha_hoy = datetime.date.today()
print("la fecha de hoy es (hecho con librería datetime):",fecha_hoy)

hoydia = np.datetime64('today')
print("la fecha de hoy es (hecho con numpy):",hoydia)


In [ ]:
# desestructurar fechas
fecha = np.datetime64('today')  # Ejemplo de fecha en formato numpy

# Obtener los componentes individuales
año = np.datetime_as_string(fecha, unit='Y')
mes = np.datetime_as_string(fecha, unit='M')
dia = np.datetime_as_string(fecha, unit='D')

print("Año:", año)
print("Mes:", mes)
print("Día:", dia)

In [9]:
# ahora desestructurado de panini, para que se pueda personalizar una fecha puntual (mas fancy)

fecha = np.datetime64('today')  # Ejemplo de fecha en formato numpy
# Obtener sólo el año
año = np.datetime_as_string(fecha, unit='Y').split('-')[0] #con el split, quitamos el guión, generando separación y desestructuramos
# Obtener solo el mes
mes = np.datetime_as_string(fecha, unit='M').split('-')[1] #con el split, quitamos el guión, generando separación y desestructuramos
# Obtener sólo el dia
dia = np.datetime_as_string(fecha, unit='D').split('-')[2] #con el split, quitamos el guión, generando separación y desestructuramos

# y ahora usaremos f strings para ahorrarnos espacio
print(f'si me preguntan que dia es hoy, estamos a {dia} del {mes} del {año}')

si me preguntan que dia es hoy, estamos a 20 del 03 del 2024


In [20]:
# acá haremos otro truco, colocar en vez de la fecha numérica, con su respectivo nombre
import calendar #libreria calendar

fecha = np.datetime64('today')  # Ejemplo de fecha en formato numpy para hoy

# Obtener el mes como nombre completo
dia_num = int(np.datetime_as_string(fecha, unit='D').split('-')[2])
mes_num = int(np.datetime_as_string(fecha, unit='M').split('-')[1])
nombre_mes = calendar.month_name[mes_num] #acá le tenía un número, mietras que le podíamos poner la variable mes_num jaja

# Obtener el año
año = np.datetime_as_string(fecha, unit='Y')

print("Mes:", nombre_mes)
print("Año:", año)
print(f"""esto sólo sale en inglés, más abajo está la formula para español, pero figuraría de la siguiente manera:
        Today is 0{mes_num} {dia_num}, {año}
        le añadí un cero, para que no se viera mal
      """)

Mes: March
Año: 2024
esto sólo sale en inglés, más abajo está la formula para español, pero figuraría de la siguiente manera:
        Today is 03 20, 2024
        le añadí un cero, para que no se viera mal
      


fecha con numpy y datetime, ojo que se puede realizar de varias formas, pero esta es la que aprovecha las variables de numpy y solo utiliza datetime para definir los dias

In [21]:
# aparte de numpy, debemos importar datetime
import datetime
import numpy as np
# FECHA CON NOMBRES EN ESPAÑOL
# Definir un diccionario de nombres de meses en español
meses_espanol = {
    1: "enero", 
    2: "febrero", 
    3: "marzo", 
    4: "abril",
    5: "mayo", 
    6: "junio", 
    7: "julio", 
    8: "agosto",
    9: "septiembre", 
    10: "octubre", 
    11: "noviembre", 
    12: "diciembre"
}
# Definir un diccionario con los dias en español para datetime
dias_semana = [
    'lunes', 
    'martes', 
    'miércoles', 
    'jueves', 
    'viernes', 
    'sábado', 
    'domingo'
]
fecha = np.datetime64('today')  # Ejemplo de fecha en formato numpy

# Obtener el mes como nombre completo en español
mes_num = int(np.datetime_as_string(fecha, unit='M').split('-')[1]) #con el split, quitamos el guión, generando separación y desestructuramos
dia_num = int(np.datetime_as_string(fecha, unit='D').split('-')[2]) #con el split, quitamos el guión, generando separación y desestructuramos
# Obtener las fechas respectivas
anio = np.datetime_as_string(fecha, unit='Y')
nombre_mes = meses_espanol[mes_num]

nombre_dia = dias_semana[datetime.date.today().weekday()] # aca se ocupa atributos de datetime + diccionario

# ahora con f strings 
print(f'Santiago, {nombre_dia} {dia_num} de {nombre_mes} de {anio}')

Santiago, miércoles 20 de marzo de 2024


In [22]:
# obtener un listado con rango de fechas (un mes para ser específico)
z = np.arange('2023-04','2023-05', dtype='datetime64[D]') #el datetime extrae los dias
divisiones = z.reshape(3,10) #donde es un array, podemos hacer reshape a ciertas fechas parejas, como las matrices 
print(z)
# y si queremos sacarle el corchete, usamos *
# print(*z)

['2023-04-01' '2023-04-02' '2023-04-03' '2023-04-04' '2023-04-05'
 '2023-04-06' '2023-04-07' '2023-04-08' '2023-04-09' '2023-04-10'
 '2023-04-11' '2023-04-12' '2023-04-13' '2023-04-14' '2023-04-15'
 '2023-04-16' '2023-04-17' '2023-04-18' '2023-04-19' '2023-04-20'
 '2023-04-21' '2023-04-22' '2023-04-23' '2023-04-24' '2023-04-25'
 '2023-04-26' '2023-04-27' '2023-04-28' '2023-04-29' '2023-04-30']


In [ ]:
# ¿Cómo calcular ((A+B)*(-A/2)) en su lugar (sin copia)?

A = np.ones(3)*1 # se crea una matriz | Resultado: A = array([1., 1., 1.])
B = np.ones(3)*2 # se crea una matriz | Resultado: B = array([2., 2., 2.])
print(f'{A} {B}')

np.add(A,B,out=B) # Suma los elementos de los arrays A y B, y guarda el resultado en B. Resultado: B = array([3., 3., 3.])
np.divide(A,2,out=A) # Resultado: A = array([0.5, 0.5, 0.5])
np.negative(A,out=A) #Resultado: A = array([-0.5, -0.5, -0.5])
np.multiply(A,B,out=A) #Resultado: A = array([-1.5, -1.5, -1.5])

In [ ]:
z = np.random.uniform(0,10,10) # un array con 10 cosas
print(z) #arroja el array con los 10 elementos 
print(z - z%1) # arroja los primeros numeros de cada elemento del array
print(z // 1) # realiza lo mismo que la función de arriba
print(np.floor(z)) # realiza lo mismo que las funciones de arriba
print(z.astype(int)) # devuelve los primeros números, pero sin los puntos, como int
print(np.trunc(z)) # truncado.


In [2]:
# genera una matriz de 4x4 con valores raw
z = np.zeros((5,5))
z +=np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
# otra alternativa, sin puntos
z = np.tile(np.arange(0,5),(5,1))
print(z)

In [ ]:
# crear una función generadora de 10 numeros y construir una matriz:
def generate():
    for x in range(100):
        yield x
z = np.fromiter(generate(),dtype=float, count=-1)
print("\narray con puntos \n",z)
# para imprimirlo sin los puntos
print("\nse eliminan los puntos \n",z.astype(int))
# como dato adicional, se puede agregar un asterisco en el print para eliminar los corchetes

In [ ]:
# crear un array con nímeros que vayan del cero al uno
z = np.linspace(0,1,11,endpoint=False)[1:]
print(z)

Ayuda en Python - para conocer las propiedades de cada cosa, podemos agregar el signo "?"

In [ ]:
np.arange? # arroja todas las propiedades del arange

In [54]:
# crear un array random con 10 elementos
z = np.random.random(10)
z.sort()
print(z)

[0.17103354 0.18827022 0.35190153 0.48140685 0.58650089 0.60037724
 0.70928371 0.80243744 0.91550436 0.92973425]


In [71]:
# sumar una matriz pequeña = suma todos los numeros
z = np.arange(10)
suma = np.add.reduce(z)
print(f"{z} = {suma}")
print(f"la suma de los números en el array es {suma}")

[0 1 2 3 4 5 6 7 8 9] = 45
la suma de los números en el array es 45


In [83]:
# Considerar 2 matrices aleatorias y ver si son iguales
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
print(f"{a} {b}")

igual = np.allclose(a,b) # ver igualdad (opcion 1)
print(igual)

igual = np.array_equal(a,b) # ver igualdad (opción 2)
print(igual)

[0 1 1 0 0] [1 0 0 1 1]
False
False
